version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5431:5431"
  web:
    build: .
    command: python /twitter/manage.py runserver 0.0.0.0:8000
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - .:/twitter
    ports:
      - "8000:8000"
    depends_on:
      - db